baseurl = "inflianskas.ru"
author = "Roman Inflianskas"
title = "Roman Inflianskas"

theme = "goa"

languagecode = "en"

[params]
    author = "Roman Inflianskas"
    intro = "Python Developer, FOSS Enthusiast"
    description = "Moscow, Russia"
    keywords = "python,developer,devops,personal"
    authorimage = "photo.jpg"

[params.social]
    github = "rominf"
    stackoverflow = "2108548"
    linkedin = "roman-inflianskas-817523b1"
    telegram = "rom_inf"
    email = "roman@inflianskas.ru"

[[menu.main]]
    name = "Resume"
    weight = 1
    url  = "roman_inflianskas_cv_en.pdf"

[[menu.main]]
    name = "hh.ru"
    weight = 2
    url  = "https://hh.ru/resume/86fdb4ddff0530d2790039ed1f6b6e31744c7a"

[[menu.main]]
    name = "Habr Career"
    weight = 3
    url  = "https://career.habr.com/rominf"
